---
AWSTemplateFormatVersion: 2010-09-09
Description: Apache stack

Parameters:
  BucketName:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08589eca6dcc9b39c
      InstanceType: t2.micro
      KeyName: default
      UserData:
        Fn::Base64:
          !Sub |
            #!/usr/bin/env bash
            index='/var/www/html/index.html'

            update_system() {
              yum -y update
            }

            configure_apache() {
              yum -y install httpd
              service httpd start
              chkconfig httpd on
              aws s3 cp s3://"${BucketName}" /var/www/html -recursive
            }

            configure_index_html() {
              echo "<h1>Deployed via CloudFormation!</h1>" | tee "$index"
            }

            main() {
              update_system
              configure_apache
              configure_index_html
            }

            if [ "$0" == "${!BASH_SOURCE[0]}" ] ; then
              main
            fi

Outputs:
  PublicIp:
    Description: Public IP
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicIp"
